name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  # Allow the use of insecure Node.js versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4  # Use the latest version available
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Linting with flake8
      run: |
        flake8 .
      
    - name: Run Tests with pytest
      run: |
        pytest --flake8
